title: ClimaTrack
theme: minima
# The following line is optional but helps if things don't show up
header_pages:
  - index.md
  - Sareak - 3.2. erronka.md
  - Markatze Erronka 3.2.md
  - Sistemas- 3.2. erronka.md
  - Digitalizazioa - 3.2. erronka.md
  - Data base - 3.2. erronka.md
