title: ClimaTrack
theme: minima
# The following line is optional but helps if things don't show up
header_pages:
  - index.md
  - Sareak.md
  - fisiko.md
  - Markatze.md
  - SistemaEragileak.md
  - Digitalizazioa.md
  - DataBase.md
